In [22]:
import numpy as np
import pandas as pd

In [1]:
from tensorflow import keras

In [2]:
(train_input,train_target),(test_input,test_target) = keras.datasets.fashion_mnist.load_data()

In [5]:
train_input[0]

array([[  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   1,
          0,   0,  13,  73,   0,   0,   1,   4,   0,   0,   0,   0,   1,
          1,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   3,
          0,  36, 136, 127,  62,  54,   0,   0,   0,   1,   3,   4,   0,
          0,   3],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   6,
          0, 102, 204, 176, 134, 144, 123,  23,   0,   0,   0,   0,  12,
         10,   0],
       [  

In [35]:
test_input[0]

array([[  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  

In [7]:
train_scaled = train_input/255
train_scaled = train_scaled.reshape(-1,28*28)

In [10]:
test_scaled = test_input/255
test_scaled = test_scaled.reshape(-1,28*28)

In [8]:
import tensorflow as tf

In [17]:
# 딥러닝 - 인공신경망
from sklearn.model_selection import train_test_split

# 머신러닝 - cross_validate : 검증세트
# 딥러닝 - cross_validate 시간너무 많이 걸림

# 딥러닝 - 훈련세트, 검증세트, 테스트세트(train,val,test)

train_scaled,val_scaled,train_target,val_target = train_test_split(
    train_scaled,train_target,test_size=0.2,random_state=42
)

In [14]:
train_scaled.shape

(48000, 784)

In [16]:
print(train_scaled.shape,train_target.shape)

(48000, 784) (48000,)


In [19]:
print(val_sclaed.shape,val_target.shape)

(12000, 784) (9600,)


In [23]:
np.unique(train_target)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=uint8)

In [24]:
# 딥러닝 훈련

# 1. dense 층

# 결과 클래스
# 10 : 결정클래스
# activation='softmax' :활성화 함수
# input_shape : 입력된 데이터 사이즈
dense = keras.layers.Dense(10,activation='softmax',input_shape = (784,))

c:\Python312\Lib\site-packages\keras\src\layers\core\dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [30]:
# 2. 모델결정
model = keras.models.Sequential([dense])
# 3. 모델설정부분
# loss : 다중분류 결과값을 원핫인코딩을 사용하지 않으면 sparse_categorical_crossentropy
# loss : 다중분류 결과값을 원핫은코딩을 사용하면 categorical_crossentropy
# 이진분류 : 원핫인코딩을 사용하지 않으면 sparse_binary_crossentropy
# 이진분류 : 원핫인코딩을 사용하면 binary_crossentropy
# metrics=['accuracy'] : 정확도
model.compile(loss='sparse_categorical_crossentropy',metrics=['accuracy'])

In [32]:
# 4. 모델훈련
# 반복횟수 : epochs
model.fit(train_scaled,train_target,epochs=5)

Epoch 1/5
1200/1200 ━━━━━━━━━━━━━━━━━━━━ 1s 471us/step - accuracy: 0.8544 - loss: 0.4318
Epoch 2/5
1200/1200 ━━━━━━━━━━━━━━━━━━━━ 1s 462us/step - accuracy: 0.8555 - loss: 0.4253
Epoch 3/5
1200/1200 ━━━━━━━━━━━━━━━━━━━━ 1s 456us/step - accuracy: 0.8563 - loss: 0.4274
Epoch 4/5
1200/1200 ━━━━━━━━━━━━━━━━━━━━ 1s 458us/step - accuracy: 0.8589 - loss: 0.4178
Epoch 5/5
1200/1200 ━━━━━━━━━━━━━━━━━━━━ 1s 467us/step - accuracy: 0.8618 - loss: 0.4148


In [33]:
# 5. 모델평가

model.evaluate(val_scaled,val_target)

300/300 ━━━━━━━━━━━━━━━━━━━━ 0s 473us/step - accuracy: 0.8677 - loss: 0.4063


[0.41738972067832947, 0.8633333444595337]

In [34]:
# 머신
# 모델결정 sc = SGDC...
# 모델훈련 sc.fit()
# 모델평가 sc.score()

In [ ]:
# 딥
# 층만들기 dense = keras.layers.Dense(10,activation='softmax',input_shape = (784,))
# model = keras.models.Sequential([dense])
# model.compile(loss='sparse_categorical_crossentropy',metrics=['accuracy'])
# model.fit(train_scaled,train_target,epochs=5)
# model.evaluate(val_scaled,val_target)