In [76]:
# from sklearn import svm,metrics
# from sklearn.neighbors import KNeighborsClassifier # 분류
# from sklearn.neighbors import KNeighborsRegressor  # 회귀-예측
from sklearn.linear_model import LinearRegression  # 선형회귀
from sklearn.preprocessing import PolynomialFeatures # 다항특성을 만들어주는 라이브러리
from sklearn.model_selection import train_test_split
import pandas as pd
import numpy as np
import random
import matplotlib.pyplot as plt
import matplotlib
matplotlib.rcParams['axes.unicode_minus'] = False  # 마이너스 표시 해결
# 한글설정
matplotlib.rcParams['font.family'] = 'Malgun Gothic' # windows 사용자
# matplotlib.rcParams['font.family'] = 'AppleGothic Gothic' # Mac사용자
matplotlib.rcParams['font.size'] = '10' # 글자크기

In [77]:
import pandas as pd
df = pd.read_csv('https://bit.ly/fish_csv')
df.head(3)

Species  Weight  Length  Diagonal   Height   Width
0   Bream   242.0    25.4      30.0  11.5200  4.0200
1   Bream   290.0    26.3      31.2  12.4800  4.3056
2   Bream   340.0    26.5      31.1  12.3778  4.6961

In [78]:
# 데이터 확인 : nan, 0, 타입, 최소값, 최대값, 값이 분포, 각 특성별 데이터 최대값
# 1. 데이터전처리 - data,target 분리
fish_input = df.iloc[:,1:].to_numpy()
fish_target = df['Species'].to_numpy()

# train,test세트 분리
train_input,test_input,train_target,test_target = train_test_split(
    fish_input,fish_target
)

# 표준화 작업
from sklearn.preprocessing import StandardScaler
ss = StandardScaler()
ss.fit(train_input)
train_scaled = ss.transform(train_input)
test_scaled = ss.transform(test_input)

In [79]:
# 2. 데이터 실습시키기
from sklearn.linear_model import LogisticRegression

lr = LogisticRegression()
lr.fit(train_scaled,train_target)

LogisticRegression()

In [80]:
# 3. 데이터 예측
predict = lr.predict(test_scaled[:5])
print(predict)

['Bream' 'Perch' 'Bream' 'Pike' 'Pike']


In [81]:
# 4. 데이터 정답률 - train,test
print(lr.score(train_scaled,train_target))
print(lr.score(test_scaled,test_target))

0.8151260504201681
0.85


In [82]:
lr.classes_

array(['Bream', 'Parkki', 'Perch', 'Pike', 'Roach', 'Smelt', 'Whitefish'],
      dtype=object)

In [91]:
# 2. 데이터 실습시키기
from sklearn.linear_model import LogisticRegression
# max_iter : 반복횟수 = 100 기본설정
# C 규제 : 올라가면 규제가 약해지고, 낮아지면 규제가 강해짐,  선형회귀 규제 - alpha값으로 지정
lr = LogisticRegression(C=20, max_iter=1000)
lr.fit(train_scaled,train_target)

LogisticRegression(C=20, max_iter=1000)

In [92]:
print(lr.score(train_scaled,train_target))
print(lr.score(test_scaled,test_target))

0.9243697478991597
0.925


In [93]:
proba = lr.predict_proba(test_scaled[:5])
print(np.round(proba,decimals=3))

[[0.998 0.001 0.    0.    0.    0.    0.001]
 [0.    0.003 0.791 0.003 0.18  0.    0.024]
 [0.992 0.005 0.    0.    0.    0.    0.003]
 [0.    0.    0.057 0.921 0.021 0.    0.001]
 [0.    0.    0.008 0.991 0.001 0.    0.   ]]


In [84]:
#### 결과값 도출 형태 분석 ####

In [85]:
predict = lr.predict(test_scaled[:5])
print(predict)

# 기울기,y절편의 값을 적용시켜서 z 점수 출력
# softMax함수를 적용해서 가장 높은 확률을 채택해서 결정함.

['Bream' 'Perch' 'Bream' 'Pike' 'Pike']


In [86]:
lr.classes_

array(['Bream', 'Parkki', 'Perch', 'Pike', 'Roach', 'Smelt', 'Whitefish'],
      dtype=object)

In [87]:
proba = lr.predict_proba(test_scaled[:5])
np.round(proba,decimals=3)

array([[0.998, 0.001, 0.   , 0.   , 0.   , 0.   , 0.001],
       [0.   , 0.003, 0.791, 0.003, 0.18 , 0.   , 0.024],
       [0.992, 0.005, 0.   , 0.   , 0.   , 0.   , 0.003],
       [0.   , 0.   , 0.057, 0.921, 0.021, 0.   , 0.001],
       [0.   , 0.   , 0.008, 0.991, 0.001, 0.   , 0.   ]])

In [88]:
decision = lr.decision_function(test_scaled[:5])
print(np.round(decision,decimals=2))

[[ 13.62   6.24  -3.81  -1.68   1.16 -22.18   6.65]
 [ -4.04  -0.86   4.85  -0.87   3.37  -3.79   1.34]
 [ 11.15   5.9   -4.25  -1.94   2.1  -18.14   5.19]
 [ -4.17  -5.79   3.96   6.74   2.94  -3.3   -0.38]
 [ -2.72  -8.22   5.12   9.88   2.37  -6.68   0.26]]


In [89]:
from scipy.special import softmax

proba = softmax(decision,axis = 1)
print(np.round(proba,decimals=3))

[[0.998 0.001 0.    0.    0.    0.    0.001]
 [0.    0.003 0.791 0.003 0.18  0.    0.024]
 [0.992 0.005 0.    0.    0.    0.    0.003]
 [0.    0.    0.057 0.921 0.021 0.    0.001]
 [0.    0.    0.008 0.991 0.001 0.    0.   ]]
